### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by nikaro** [dmippolitov/pydnsbl#1]
Hello,
Could you publish a new release on PyPI with the fix for broken provider?
Thank you.

**Comment by dmippolitov** [comment]
Hi, no problem, will do on this week.

ср, 30 мая 2018 г., 11:47 Nicolas Karolak <notifications@github.com>:

**Comment by dmippolitov** [comment]
new version (0.6.2) with fixed providers uploaded on pip
