### ISSUE TITLE
False positives for dynip.rothen.com

### ISSUE THREAD

**Issue by Simon-the-Sorcerer** [dmippolitov/pydnsbl#15]
Can you remove [http://dynip.rothen.com/](http://dynip.rothen.com/) from the `BASE_PROVIDERS`? 

The domain is down/under construction.

**Comment by dmippolitov** [comment]
Fixed in 1.1.1 https://github.com/dmippolitov/pydnsbl/commit/87149faef34ded0e80cf30fbd75f6b3d023f26d8
