### ISSUE TITLE
There is no current event loop in thread 'Dummy-1'. - FIXED FOR YOU :)

### ISSUE THREAD

**Issue by moak44** [dmippolitov/pydnsbl#2]
Within checker.py line 86:
## self._loop = asyncio.get_event_loop()

Replace with:
## asyncio.set_event_loop(self._loop)

This fixed my issue. See below thread for more info:
https://stackoverflow.com/questions/41594266/asyncio-with-django/46140106

Great job and thanks! Would you mind updating and pushing to PIP?

**Comment by dmippolitov** [comment]
Hi. Thanks for reporting. I will explore a problem.
