### ISSUE TITLE
RuntimeError when running in Jupyter

### ISSUE THREAD

**Issue by adcoh** [dmippolitov/pydnsbl#20]
Working in JupyterLab, Python 3.8.
Using pydnsbl.DNSBLDomainChecker().check() function and it throws Runtime error.

```RuntimeError                              Traceback (most recent call last)
<ipython-input-11-bdf0be99db20> in <module>
      1 checker = pydnsbl.DNSBLDomainChecker()
----> 2 result = checker.check(domain)

/volumes/code/.venv/lib/python3.8/site-packages/pydnsbl/checker.py in check(self, request)
    146 
    147     def check(self, request):
--> 148         return self._loop.run_until_complete(self.check_async(request))
    149 
    150     def bulk_check(self, requests):

/usr/local/lib/python3.8/asyncio/base_events.py in run_until_complete(self, future)
    590         """
    591         self._check_closed()
--> 592         self._check_running()
    593 
    594         new_task = not futures.isfuture(future)

/usr/local/lib/python3.8/asyncio/base_events.py in _check_running(self)
    550     def _check_running(self):
    551         if self.is_running():
--> 552             raise RuntimeError('This event loop is already running')
    553         if events._get_running_loop() is not None:
    554             raise RuntimeError(

RuntimeError: This event loop is already running```

**Comment by dmippolitov** [comment]
Hi! Could you provide me some additional code snippet with more context so I will be able to reproduce it?

**Comment by adcoh** [comment]
The full code snippet is
```
import pydnsbl
checker = pydnsbl.DNSBLDomainChecker()
result = checker.check('google.com')
print(result)
```
I get the error only when running it in a Jupyter Notebook.
Running it in command line and in Pycharm it returns `<DNSBLResult: google.com  (0/4)>`

**Comment by Ravineesh** [comment]
I'm facing the same issue when running the [code](https://github.com/dmippolitov/pydnsbl/issues/20#issuecomment-852774366) in Jupyter Notebook.

**Comment by srnittoor** [comment]
Were you guys able to resolve this issue? I am having the same issue too in Notebook

actual_url = 'cnn.com'
ip = socket.gethostbyname(actual_url)
ip_checker = pydnsbl.DNSBLIpChecker()
print(ip)
ip_checker.check(ip)

**Comment by ishansaurav** [comment]
Just checking, is there an update ? Was anyone able to resolve this ?

**Comment by srnittoor** [comment]
I think it is a stubborn Jupyter issue. I had to write a separate script on Pycharm.

**Comment by dmippolitov** [comment]
Looks like Jupyter uses event-loop itself ant it's not possible to create nested loops, so that leads to errors described above. Take a look at this article please: https://medium.com/@vyshali.enukonda/how-to-get-around-runtimeerror-this-event-loop-is-already-running-3f26f67e762e
[nest_asyncio](https://github.com/erdewit/nest_asyncio) looks like possible workaround for Jupyter notebooks.
