### ISSUE TITLE
Feature request: make is possible to check a domain name

### ISSUE THREAD

**Issue by ant1** [dmippolitov/pydnsbl#7]
domain names can be checked in the dbl.spamhaus.org zone for instance
https://www.spamhaus.org/faq/section/Spamhaus%20DBL

**Comment by dmippolitov** [comment]
Will think about it. What other lists beside spamhaus can we use for domain checking?

**Comment by ant1** [comment]
the multi.surbl.org zone is  able to check domains according to:
http://www.surbl.org/guidelines  step 4

There is SEM-URI in the uribl.spameatingmonkey.net zone:
https://spameatingmonkey.com/services/SEM-URI

There is rhsbl.sorbs.net zone,  see:
http://www.sorbs.net/using.shtml

**Comment by dmippolitov** [comment]
Thank you for providing this lists. 
Just released 1.0 version with DNSBLDomainChecker class to check domains - please read new README.md for usage. Old-style usage still works but will be deprecated.

**Comment by dmippolitov** [comment]
closed 50546378294bf88d83d99be08f84cea8171a8ebf
